contracts were created
UUsatova/MLMTask pull request #1
Opened 2022-07-21 12:11 UTC by UUsatova

2022-07-21 12:46 UTC, kuriloalexey commented
название ветки

2022-07-21 12:50 UTC, kuriloalexey requested changes

2022-07-21 12:50 UTC, kuriloalexey commented on contracts/MLMLevelLogic.sol
> +pragma solidity ^0.8.9;
думаю можно поднять больше версию

2022-07-21 12:50 UTC, kuriloalexey commented on contracts/MLMLevelLogic.sol
> +        else return 10;
может лучше это сделать динамически?

2022-07-21 12:50 UTC, kuriloalexey commented on contracts/MLMLevelLogic.sol
> +        else return 10;
если 50 lvl то не хочется писать 50 if else

2022-07-21 12:50 UTC, kuriloalexey commented on contracts/MLMLevelLogic.sol
> +        if (i == 4) return 2;
а если они будут менять?
это сейчас они просто похожие

2022-07-21 12:50 UTC, kuriloalexey commented on contracts/MLMsistem.sol
> +error insufficient__funds();
не уверен что это прям нужно

2022-07-21 12:50 UTC, kuriloalexey commented on contracts/MLMsistem.sol
> +    uint s_contractAccount;
почему s?
просто все перемененные в контракте объявлены и так в storage

2022-07-21 12:50 UTC, kuriloalexey commented on contracts/MLMsistem.sol
> +        s_contractAccount = s_contractAccount + (msg.value * 5) / 100;
для чего эта логика?

2022-07-22 06:22 UTC, UUsatova commented on contracts/MLMLevelLogic.sol
> +pragma solidity ^0.8.9;
+

2022-07-22 08:29 UTC, UUsatova commented on contracts/MLMsistem.sol
> +    uint s_contractAccount;
убрала

2022-07-22 08:29 UTC, UUsatova commented on contracts/MLMLevelLogic.sol
> +        else return 10;
+

2022-07-22 08:30 UTC, UUsatova commented on contracts/MLMLevelLogic.sol
> +        if (i == 4) return 2;
+

2022-07-22 09:31 UTC, closed without merging