Feature
UUsatova/MLMTask pull request #2
Opened 2022-07-22 09:33 UTC by UUsatova

2022-07-22 10:22 UTC, kuriloalexey commented
название ветки

2022-07-22 12:12 UTC, kuriloalexey requested changes

2022-07-22 12:12 UTC, kuriloalexey commented on contracts/MLMLevelLogicInterface.sol
> +interface MLMLevelLogicInterface {
`IMLMLevelLogic`

2022-07-22 12:12 UTC, kuriloalexey commented on contracts/MLMLevelLogicInterface.sol
> +    function getLevelBySum(uint sum) external view returns (uint);
uint256 or uint32?

2022-07-22 12:12 UTC, kuriloalexey commented on contracts/MLMsistem.sol
> +contract MLMsistem {
`MLMSystem`

2022-07-22 12:12 UTC, kuriloalexey commented on contracts/MLMsistem.sol
> +    mapping(address => address[]) private usersDirPartner;
лучше полное название

2022-07-22 12:12 UTC, kuriloalexey commented on contracts/MLMsistem.sol
> +    mapping(address => uint) private usersAccounts;
uint256?

2022-07-22 12:12 UTC, kuriloalexey commented on contracts/MLMsistem.sol
> +    function withdrawMoney() public {
почему public?

2022-07-22 12:12 UTC, kuriloalexey commented on contracts/MLMLevelLogic.sol
> +    uint[] private percentOnDipth;
`percentOnDepth`

2022-07-22 12:13 UTC, kuriloalexey commented
Нудно еще подумать насчет названия функций и переменных, что б они говорили сами за себя что делают

2022-07-22 12:35 UTC, kuriloalexey requested changes

2022-07-22 12:35 UTC, kuriloalexey commented on contracts/MLMLevelLogicInterface.sol
> +interface MLMLevelLogicInterface {
`IMLMLevelLogic`
Все интрефейсы в отдельной директории

2022-07-25 19:10 UTC, UUsatova commented on contracts/MLMsistem.sol
> +contract MLMsistem {
я дурачок

2022-07-25 19:39 UTC, closed without merging